export enum Role {
    SYSTEM_ADMIN = 'SYSTEM_ADMIN',
    STUDENT = 'STUDENT',
    UNIVERSITY_ADMIN = 'UNIVERSITY_ADMIN',
    COLLEGE_DEAN = 'COLLEGE_DEAN',
    DEPARTMENT_HEAD = 'DEPARTMENT_HEAD',
    COMPANY_HR = 'COMPANY_HR',
    ADVISOR = 'ADVISOR',
    MENTOR = 'MENTOR',   
}